using System;
using System.Collections.Generic;
using System.Linq;
using VideoGameBlog.Models;
using VideoGameBlog.Models.Tables;

namespace VideoGameBlog.Data.InMemory
{
	public class InMemoryPostRepository : IVideoGameBlogRepository<Post>
	{
		private static InMemoryCategoryRepository categoryRepository = new InMemoryCategoryRepository();
		private static InMemoryTagRepository tagRepository = new InMemoryTagRepository();

		private static List<Post> posts = new List<Post>
		{
            new Post{Id = 1, PostState = PostState.Post, Username = "devteam",PostCategory = categoryRepository.Get(1), PostedDate = DateTime.Now.AddDays(-7), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll(), PostTitle = "Fallout 4 VR is sub-revolutionary",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 2, PostState = PostState.Post, Username = "devteam",PostCategory = categoryRepository.Get(2), PostedDate = DateTime.Now.AddMonths(-7), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 2 == 0).ToList(), PostTitle = "Blah blah blah video game stuff",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 3, PostState = PostState.Post, Username = "devteam",PostCategory = categoryRepository.Get(3), PostedDate = DateTime.Now.AddYears(-7), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 3 == 0).ToList(), PostTitle = "Please give me a break I'm so tired",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 4, PostState = PostState.Post, Username = "devteam",PostCategory = categoryRepository.Get(4), PostedDate = DateTime.Now.AddDays(-3), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 4 == 0).ToList(), PostTitle = "God kill me my back hurts",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 5, PostState = PostState.Post, Username = "devteam",PostCategory = categoryRepository.Get(1), PostedDate = DateTime.Now.AddMonths(-3), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 5 == 0).ToList(), PostTitle = "I have some seriously dangerous gas",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 6, PostState = PostState.Post, Username = "testmarketing",PostCategory = categoryRepository.Get(2), PostedDate = DateTime.Now.AddYears(-3), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll(), PostTitle = "I have been holding it this whole time",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 7, PostState = PostState.Pending, Username = "testmarketing",PostCategory = categoryRepository.Get(3), PostedDate = DateTime.Now, PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 2 == 0).ToList(), PostTitle = "I need to get more coffee to remain conscious",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 8, PostState = PostState.Pending, Username = "testmarketing",PostCategory = categoryRepository.Get(4), PostedDate = DateTime.Now.AddDays(-14), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 3 == 0).ToList(), PostTitle = "I wonder if I will be able to get sleep tonight",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 9, PostState = PostState.Pending, Username = "testmarketing",PostCategory = categoryRepository.Get(1), PostedDate = DateTime.Now.AddMonths(-14), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 4 == 0).ToList(), PostTitle = "I need a stiff drink",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" },
            new Post{Id = 10, PostState = PostState.Denied, Username = "testmarketing",PostCategory = categoryRepository.Get(2), PostedDate = DateTime.Now.AddYears(-14), PostImageFileName = "placeholder.png", PostTags = tagRepository.GetAll().Where(t => t.Id % 5 == 0).ToList(), PostTitle = "Capstones are fun",
                PostBody = @"<p>Ballast rope's end Plate Fleet pillage lugger gangplank nipper hornswaggle quarterdeck transom grog tender yo-ho-ho chandler aye warp code of conduct lad spanker Jolly Roger. Gabion swing the lead Sail ho parley haul wind rum Jack Ketch gun skysail black jack ahoy trysail scallywag gangway yawl strike colors measured fer yer chains fore chantey sutler. Run a rig parley gaff poop deck crow's nest Corsair gabion tender jury mast pressgang rum loot ballast lookout bucko clap of thunder Arr piracy take a caulk sheet. Rutters hail-shot hearties bilge rat lanyard parley gangplank Spanish Main topgallant splice the main brace hands come about capstan league port barkadeer log draft Letter of Marque black spot. Lee heave to keel spyglass reef ahoy swing the lead pirate Sink me quarter tender bilge rat Shiver me timbers barque jury mast American Main salmagundi pillage Corsair furl.</p>
                <p>Warp carouser hulk ye overhaul fore bilge yard loaded to the gunwalls gunwalls schooner me landlubber or just lubber square-rigged bounty pinnace wench scuttle spanker long clothes. Chantey lateen sail fire in the hole spyglass bilge water jack matey Letter of Marque blow the man down lookout ahoy red ensign draft pirate keel hail-shot come about brigantine crow's nest run a rig. Me grog blossom square-rigged heave to bilge water Corsair maroon gabion gally furl ballast fire ship tackle hearties Arr nipper matey ho fore strike colors. Hogshead Nelsons folly case shot schooner boom coxswain bilge rat furl rigging tack bowsprit topsail pinnace provost piracy ballast jolly boat scuttle league line. Strike colors starboard jury mast long boat gunwalls black jack plunder Sea Legs ho loaded to the gunwalls matey pressgang swab avast chandler code of conduct warp gangway bucko brigantine.</p>
                <p>Draft scurvy fore dead men tell no tales swing the lead league boatswain Davy Jones' Locker schooner Gold Road grog blossom port aft cutlass avast spirits skysail brig grog careen. Ahoy list poop deck chantey weigh anchor aft Spanish Main doubloon Cat o'nine tails Gold Road Sail ho bring a spring upon her cable gaff skysail heave to gabion galleon hempen halter line gunwalls. Brig gun bounty Buccaneer Plate Fleet tackle mizzenmast marooned Sail ho Blimey hands lateen sail scuppers aft ahoy Chain Shot reef transom tender pressgang. Walk the plank yardarm booty nipperkin pirate hulk execution dock fluke scourge of the seven seas gun Sail ho code of conduct fire in the hole gabion case shot hogshead Barbary Coast handsomely measured fer yer chains topgallant. Furl pink blow the man down scuppers handsomely Jack Ketch provost chase guns jib walk the plank Privateer grapple heave down capstan man-of-war carouser swab Barbary Coast black jack Pieces of Eight.</p>
                <p>Sutler sheet haul wind reef sails boom doubloon Yellow Jack wench bucko grog blossom swab spike lass fluke loot splice the main brace Shiver me timbers grapple code of conduct gibbet. Scuppers belay Jolly Roger smartly rutters lad red ensign weigh anchor wherry gally keelhaul ye booty careen black spot keel me topmast run a shot across the bow hail-shot. Bilge water careen loot wench overhaul parrel fathom poop deck hardtack belay knave dead men tell no tales squiffy black jack starboard ye skysail Corsair loaded to the gunwalls scuppers. Cackle fruit topmast reef sails bowsprit gangplank fluke warp no prey, no pay scallywag keelhaul prow dead men tell no tales hornswaggle case shot lugsail killick snow gunwalls bilge water Davy Jones' Locker. Salmagundi square-rigged execution dock grog blossom aye keel plunder bounty lad Brethren of the Coast lookout wench run a shot across the bow lugsail hang the jib skysail Spanish Main tack warp crow's nest.</p>
                <p>Coffer man-of-war skysail scourge of the seven seas aye crack Jennys tea cup yo-ho-ho Plate Fleet gally Jolly Roger draught fire ship rum clap of thunder transom lanyard stern ye parley hail-shot. Carouser holystone American Main avast keel clap of thunder sheet jib nipperkin loaded to the gunwalls gibbet bilge water Cat o'nine tails long boat to go on account piracy cable square-rigged Sink me scourge of the seven seas. Scourge of the seven seas topsail cable marooned run a rig mizzen walk the plank skysail brigantine barkadeer nipper Corsair ahoy execution dock schooner belaying pin crimp Jolly Roger pink rum. Clap of thunder man-of-war parley long boat run a shot across the bow log long clothes topmast ho nipperkin Pieces of Eight take a caulk spanker chase piracy Admiral of the Black jack swab gun lookout. Jack Ketch jolly boat six pounders gangplank square-rigged Plate Fleet provost boatswain fluke lad hornswaggle draught main sheet dead men tell no tales bilged on her anchor tackle lookout gangway pressgang barque.</p>" }
        };

		public void Add(Post newItem)
		{
			newItem.Id = posts.Max(i => i.Id) + 1;
			posts.Add(newItem);
		}

		public void Delete(int id)
		{
			var existing = Get(id);
			if (existing == null)
			{
				return;
			}
			posts.Remove(existing);
		}

		public void Edit(Post item)
		{
			var existing = Get(item.Id);
			if (existing == null)
			{
				return;
			}
			existing.PostBody = item.PostBody;
			existing.PostCategory = item.PostCategory;
			existing.PostedDate = item.PostedDate;
			existing.PostImageFileName = item.PostImageFileName;
			existing.PostTags = item.PostTags;
			existing.PostTitle = item.PostTitle;
		}

		public Post Get(int id)
		{
			return posts.FirstOrDefault(i => i.Id == id);
		}

		public IList<Post> GetAll()
		{
			return posts;
		}
	}
}