USE [C:\REPOS\COONOR-GLEASON-INDIVIDUAL-WORK\WEBAPPLICATION1\WEBAPPLICATION1\APP_DATA\DVDS.MDF]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_getDvd]
	@id int
AS
	SELECT * FROM DVDS WHERE ID = @id
